### ISSUE TITLE
Merge good external "Anatomy of SSSD" documentation

### ISSUE THREAD

**Issue by elkoniu** [SSSD/sssd.io#18]
@alexey-tikhonov pointed me interesting article made by @jhrozek on his blog:
https://jhrozek.wordpress.com/2015/03/11/anatomy-of-sssd-user-lookup/
This article is from 2015 but it still contains a lots of useful information.
If @jhrozek agree maybe we may want to include this in our new documentation?

**Comment by pbrezina** [comment]
Something like this was done in the architecture page.
