### ISSUE TITLE
Document running under GDB

### ISSUE THREAD

**Issue by mikhailnov** [SSSD/sssd.io#49]
"Reporting bugs" doc says some words about GDB
https://sssd.io/docs/reporting-bugs.html
but it is not clear how to really debug sssd.

What I am trying to do is somehow attach to krb5_child and debug it.

It woild be very nice to document an example.

**Comment by alexey-tikhonov** [comment]
`krb5_child` is a short living process, run on demand to complete single action only.

Perhaps you can attach to parent process and enable `follow-fork-mode child` (https://sourceware.org/gdb/onlinedocs/gdb/Forks.html)

**Comment by mikhailnov** [comment]
> `krb5_child` is a short living process, run on demand to complete single action only.
> 
> Perhaps you can attach to parent process and enable `follow-fork-mode child` (https://sourceware.org/gdb/onlinedocs/gdb/Forks.html)

I want to debug why I get "Cannot find KDC for realm XXX", this is an error from libkrb5, it is also logged in  /var/log/sssd/krb5_child.log. I want to make a break point in `static krb5_error_code get_and_save_tgt` in sssd's krb_child.c end then probably somewhere in libkrb5.

If attaching to the parent process, the question is the same: how to do it? It is called from under PAM stack via dbus. Or do you suggest to run sssd daemon manually instead of systemd?

**Comment by pbrezina** [comment]
You can either attach to `sssd_be` (`gdb program $(pidof sssd_be`) and use the `follow-fork-mode` as suggested by Alexey. Or you can also use `gdbserver` ([example](https://stackoverflow.com/questions/48452183/debug-using-gdb-the-initial-startup-of-a-linux-daemon))

**Comment by pbrezina** [comment]
But it is certainly a good topic to document.

**Comment by mikhailnov** [comment]
@pbrezina I tried gdbserver but probably incorrectly. I did:

mv /usr/libexec/sssd/krb5_child /usr/libexec/sssd/krb5_child.bin

and created an executable script /usr/libexec/sssd/krb5_child:

#!/bin/sh
gdbserver localhost:9000 /usr/libexec/sssd/krb5_child.bin "$@"

And got strange things after attaching to that gdbserver

**Comment by alexey-tikhonov** [comment]
> If attaching to the parent process, the question is the same: how to do it? It is called from under PAM stack via dbus.

`krb5_child` is executed by the `sssd_be --domain $domain` of the domain you authenticate against.

> Or do you suggest to run sssd daemon manually instead of systemd or attach to it via PID?

Why? I think You can attach to already running process, even if it is started by systemd.

**Comment by mikhailnov** [comment]
Hm, I've attached to sssd_be:
`gdb -p $(pgrep sssd_be)`
`set follow-fork-mode child`

Then try to run `su - user01@domain.tld` in another console and it freezes, what should be done in gdb after setting follow-fork-mode? 

(No debugging symbols found in .gnu_debugdata for /usr/lib64/samba/libwinbind-client-samba4.so)

0x00007f51dbe70b46 in epoll_wait () from /lib64/libc.so.6
(gdb) c
Continuing.

Program received signal SIG34, Real-time event 34.
0x00007f51dbe70b46 in epoll_wait () from /lib64/libc.so.6
(gdb) c
Continuing.

Program received signal SIG34, Real-time event 34.
0x00007f51dbe70b46 in epoll_wait () from /lib64/libc.so.6
(gdb) b krb5_child.c:1
No source file named krb5_child.c.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (krb5_child.c:1) pending.
(gdb) c
Continuing.

Program received signal SIGTERM, Terminated.
0x00007f51dbd9f1e7 in kill () from /lib64/libc.so.6
(gdb) c
Continuing.
[Inferior 1 (process 1884) exited with code 0106]
(gdb) 

and after that a password promt appears where `su` was run

**Comment by mikhailnov** [comment]
I've managed to attach to krb5_child using gdbserver:

`mv -v /usr/libexec/sssd/krb5_child /usr/libexec/sssd/krb5_child.bin`

Created a script `/usr/libexec/sssd/krb5_child`:

```bash
#!/bin/sh
gdbserver localhost:9000 /usr/libexec/sssd/krb5_child.bin "$@"
```

`chmod +x /usr/libexec/sssd/krb5_child`

But setting `timeout` as suggested in https://sssd.io/docs/reporting-bugs.html seems to not work. My sssd.conf is the following:

```
# cat /etc/sssd/sssd.conf
[domain/ipa.loc]

id_provider = ipa
ipa_server = _srv_, ipasrv1.ipa.loc
ipa_domain = ipa.loc
ipa_hostname = client1.ipa.loc
auth_provider = ipa
chpass_provider = ipa
access_provider = ipa
cache_credentials = True
ldap_tls_cacert = /etc/ipa/ca.crt
dyndns_update = True
dyndns_iface = enp1s0
krb5_store_password_if_offline = True
timeout = 900
[sssd]
services = nss, pam, ssh, sudo
domains = ipa.loc
[nss]
homedir_substring = /home

[pam]

[sudo]

[autofs]

[ssh]

[pac]
[ifp]

[secrets]

[session_recording]
```

but krb5_child seems to be killed very quickly, I have only about ~10 seconds to make something in gdb.

**Comment by pbrezina** [comment]
I think you need to increase krb5_auth_timeout (defaults to 6 seconds).

**Comment by pbrezina** [comment]
Hi, thank you for sharing this. Using gdbserver should be denifinetly possible. We'll keep this around and document it sometime after holidays.

**Comment by mikhailnov** [comment]
Thanks!
