### ISSUE TITLE
Improvement in sssctl analyze documentation about how the Requests IDs (CID) are tracked in nss and pam responder

### ISSUE THREAD

**Issue by shridhargadekar** [SSSD/sssd.io#51]
Addition of a documentation section or details about following points in the 'sssctl analyze request list/show' will be helpful
1. 'sssctl analyze' tracks a user/group information(id, getent) in nss responder independent of a user authentication(su, ssh) request in pam responder.  Thus CID number for nss and pam will be different. CID for id/getent may differ from CID for ssh/su.
2. 'sssctl analyze' requires 'debug_level' option in the [nss] and [pam] to track/parse the logs related to user-information(NSS) and user authentication respectively.
3. 'sssctl analyze' requires 'debug_level' option in [domain/<dom>] to parse the child log(krb5, gpo) files. Without debug_level in domain section will not enable 'sssctl analyze' to parse the child logs.

**Comment by sumit-bose** [comment]
> Addition of a documentation section or details about following points in the 'sssctl analyze request list/show' will be helpful
> 
>     1. 'sssctl analyze' tracks a user/group information(id, getent) in nss responder independent of a user authentication(su, ssh) request in pam responder.  Thus CID number for nss and pam will be different. CID for id/getent may differ from CID for ssh/su.
> 

Hi,

do you mean that it should be made clear that the CID is counted independently for nss and pam requests, e.g. mention that both will start with `0` if SSSD is restarted?


>     2. 'sssctl analyze' requires 'debug_level' option in the [nss] and [pam] to track/parse the logs related to user-information(NSS) and user authentication respectively.
> 
>     3. 'sssctl analyze' requires 'debug_level' option in [domain/] to parse the child log(krb5, gpo) files. Without debug_level in domain section will not enable 'sssctl analyze' to parse the child logs.

Ok, since this is a log analyzer feature you need logs first which implies that `debug_level` is set to a suitable value. But I agree it is better to mention it explicitly.

bye,
Sumit

**Comment by shridhargadekar** [comment]
By the 'CID count is independentaly', I meant, CID requests for NSS and PAM are differently tracked.
e.g. If
```
# sssctl analyze request list -v        
cid #1 for id amy-admin
cid #2 'id administrator'
cid #4 ssh administrator
```
Above output shows  CID #1 for 'id amy-admin'
Above command shows 'cid #4' for 'ssh administrator'
```
#sssctl analyze request list --pam -v 
CID #1 for 'ssh administrator'

```
Above shows 'cid #1' for ssh. The CID#1
As per Justin,
<snip>
You will see overlapping CID numbers, the first request triggers the NSS responder and it will be CID #1, when a request triggers PAM responder it will be CID #1 as well
</snip>

**Comment by justin-stephenson** [comment]
Submitted https://github.com/SSSD/sssd.io/pull/52 to address these comments. @shridhargadekar can you please see if it is acceptable for you?
