### ISSUE TITLE
Incorrect grammar

### ISSUE THREAD

**Issue by iandstanley** [SSSD/sssd.io#62]
https://github.com/SSSD/sssd.io/blob/master/src/docs/quick-start.rst

As your intent is likely for people to use the quickstart guide as a template to start their own sssd installation, you should change the **i.e.**  to  **e.g.**.

i.e. would imply that there is only one possible setting. And as the end user does not own the domain specified (sssd.io) that would contradict the documentation.

e.g. provides an example which is following in the worked example below

**Comment by andreboscatto** [comment]
@pbrezina this is already fixed, right? Or should we change something else?

**Comment by pbrezina** [comment]
It looks to be fixed, yes.
